name: Automated Tests

on:
  push:
    branches: [ "main", "develop", "testing" ] 
  pull_request:
    branches: [ "main", "develop"]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./SHA3-512
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
